apiVersion: v1
kind: Namespace
metadata:
  name: oomkilled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oomkilled
  labels:
    app: oomer
  name: oomer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oomer
  template:
    metadata:
      labels:
        app: oomer
    spec:
      containers:
      - image: ghcr.io/jdockerty/oomer:0.0.2
        name: oomer-128-128
        terminationMessagePath: "/tmp/oomed-pod.log"
        resources:
          requests:
            cpu: '100m'
            memory: '128Mi'
          limits:
            cpu: '100m'
            memory: '128Mi'
      - image: ghcr.io/jdockerty/oomer:0.0.2
        name: oomer-50-50
        terminationMessagePath: "/tmp/oomed-pod.log"
        resources:
          requests:
            cpu: '100m'
            memory: '50Mi'
          limits:
            cpu: '100m'
            memory: '50Mi'
      - image: ghcr.io/jdockerty/oomer:0.0.2
        name: oomer-100-100
        terminationMessagePath: "/tmp/oomed-pod.log"
        resources:
          requests:
            cpu: '100m'
            memory: '100Mi'
          limits:
            cpu: '100m'
            memory: '100Mi'
      - image: ghcr.io/jdockerty/oomer:0.0.2
        name: oomer-50-100
        terminationMessagePath: "/tmp/oomed-pod.log"
        resources:
          requests:
            cpu: '100m'
            memory: '50Mi'
          limits:
            cpu: '100m'
            memory: '100Mi'
      - image: ghcr.io/jdockerty/oomer:0.0.2
        name: oomer-200-200
        terminationMessagePath: "/tmp/oomed-pod.log"
        resources:
          requests:
            cpu: '100m'
            memory: '200Mi'
          limits:
            cpu: '100m'
            memory: '200Mi'
      - image: ghcr.io/jdockerty/oomer:0.0.2
        name: oomer-100-200
        terminationMessagePath: "/tmp/oomed-pod.log"
        resources:
          requests:
            cpu: '100m'
            memory: '100Mi'
          limits:
            cpu: '100m'
            memory: '200Mi'
